#
# Auto generated makefile
#

all:
	$(MAKE) -f makefile.am263px libs
	$(MAKE) -f makefile.am263px examples

clean: libs-clean examples-clean
scrub: libs-scrub examples-scrub

help:
	@echo  Notes,
	@echo  - Use -j to invoke parallel builds
	@echo  - Use PROFILE=debug or PROFILE=release [default] to build in debug or release profile
	@echo  .
	@echo  Overall build targets,
	@echo  ======================
	@echo  $(MAKE) -s -f makefile.am263px help
	@echo  .
	@echo  $(MAKE) -s -f makefile.am263px all
	@echo  $(MAKE) -s -f makefile.am263px clean  # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.am263px scrub  # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  $(MAKE) -s -f makefile.am263px libs
	@echo  $(MAKE) -s -f makefile.am263px libs-clean # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.am263px libs-scrub # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  $(MAKE) -s -f makefile.am263px examples
	@echo  $(MAKE) -s -f makefile.am263px examples-clean # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.am263px examples-scrub # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  Library build targets,
	@echo  ======================
	@echo  $(MAKE) -s -f makefile.am263px ethercat_slave_icss_fwhal_r5f.ti-arm-clang
	@echo  $(MAKE) -s -f makefile.am263px ethernetip_adapter_mii_icss_fwhal_r5f.ti-arm-clang
	@echo  $(MAKE) -s -f makefile.am263px ethernetip_adapter_lwip_contrib_r5f.ti-arm-clang
	@echo  $(MAKE) -s -f makefile.am263px ethernetip_adapter_lwip_freertos_r5f.ti-arm-clang
	@echo  $(MAKE) -s -f makefile.am263px profinet_device_irt_mii_icss_fwhal_r5f.ti-arm-clang
	@echo  $(MAKE) -s -f makefile.am263px profinet_device_rt_mrp_mii_icss_fwhal_r5f.ti-arm-clang
	@echo  .
	@echo  Library clean targets,
	@echo  ======================
	@echo  $(MAKE) -s -f makefile.am263px ethercat_slave_icss_fwhal_r5f.ti-arm-clang_clean
	@echo  $(MAKE) -s -f makefile.am263px ethernetip_adapter_mii_icss_fwhal_r5f.ti-arm-clang_clean
	@echo  $(MAKE) -s -f makefile.am263px ethernetip_adapter_lwip_contrib_r5f.ti-arm-clang_clean
	@echo  $(MAKE) -s -f makefile.am263px ethernetip_adapter_lwip_freertos_r5f.ti-arm-clang_clean
	@echo  $(MAKE) -s -f makefile.am263px profinet_device_irt_mii_icss_fwhal_r5f.ti-arm-clang_clean
	@echo  $(MAKE) -s -f makefile.am263px profinet_device_rt_mrp_mii_icss_fwhal_r5f.ti-arm-clang_clean
	@echo  .
	@echo  Example build targets,
	@echo  ======================
	@echo  $(MAKE) -s -C examples/industrial_comms/ethercat_slave_beckhoff_ssc_demo/am263px-lp/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/industrial_comms/ethercat_slave_beckhoff_ssc_demo/am263px-cc/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/industrial_comms/ethercat_slave_demo/device_profiles/402_cia/am263px-lp/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/industrial_comms/ethercat_slave_demo/device_profiles/ctt/am263px-lp/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/industrial_comms/ethercat_slave_demo/device_profiles/401_simple/am263px-lp/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/industrial_comms/ethernetip_adapter_demo/device_profiles/generic_device/mii/am263px-lp/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/industrial_comms/ethernetip_adapter_demo/device_profiles/discrete_io_device/mii/am263px-lp/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  .
	@echo  System Example build targets,
	@echo  =============================
	@echo  .

# Various Component Targets
BUILD_COMBO_ethercat_slave_icss_fwhal = ethercat_slave_icss_fwhal_r5f.ti-arm-clang
BUILD_COMBO_ethernetip_adapter_mii_icss_fwhal = ethernetip_adapter_mii_icss_fwhal_r5f.ti-arm-clang
BUILD_COMBO_ethernetip_adapter_lwip_contrib = ethernetip_adapter_lwip_contrib_r5f.ti-arm-clang
BUILD_COMBO_ethernetip_adapter_lwip_freertos = ethernetip_adapter_lwip_freertos_r5f.ti-arm-clang
BUILD_COMBO_profinet_device_irt_mii_icss_fwhal = profinet_device_irt_mii_icss_fwhal_r5f.ti-arm-clang
BUILD_COMBO_profinet_device_rt_mrp_mii_icss_fwhal = profinet_device_rt_mrp_mii_icss_fwhal_r5f.ti-arm-clang

# Combine all Components
BUILD_COMBO_ALL = $(BUILD_COMBO_ethercat_slave_icss_fwhal) $(BUILD_COMBO_ethernetip_adapter_mii_icss_fwhal) $(BUILD_COMBO_ethernetip_adapter_lwip_contrib) $(BUILD_COMBO_ethernetip_adapter_lwip_freertos) $(BUILD_COMBO_profinet_device_irt_mii_icss_fwhal) $(BUILD_COMBO_profinet_device_rt_mrp_mii_icss_fwhal)

# Combine all Pre-built Components
BUILD_COMBO_PREBUILT_ALL =

# Combine all Private Components
BUILD_COMBO_PRIVATE_ALL =

libs: $(BUILD_COMBO_ALL)

libs-prebuilt: $(BUILD_COMBO_PREBUILT_ALL)

libs-private: $(BUILD_COMBO_PRIVATE_ALL)

$(BUILD_COMBO_ethercat_slave_icss_fwhal):
	$(MAKE) -C source/industrial_comms/ethercat_slave/icss_fwhal -f makefile.am263px.$(subst ethercat_slave_icss_fwhal_,,$@) all

$(BUILD_COMBO_ethernetip_adapter_mii_icss_fwhal):
	$(MAKE) -C source/industrial_comms/ethernetip_adapter/icss_fwhal -f makefile.mii.am263px.$(subst ethernetip_adapter_mii_icss_fwhal_,,$@) all

$(BUILD_COMBO_ethernetip_adapter_lwip_contrib):
	$(MAKE) -C source/industrial_comms/ethernetip_adapter/stack/lwip -f makefile.contrib.am263px.$(subst ethernetip_adapter_lwip_contrib_,,$@) all

$(BUILD_COMBO_ethernetip_adapter_lwip_freertos):
	$(MAKE) -C source/industrial_comms/ethernetip_adapter/stack/lwip -f makefile.stack.am263px.$(subst ethernetip_adapter_lwip_freertos_,,$@) all

$(BUILD_COMBO_profinet_device_irt_mii_icss_fwhal):
	$(MAKE) -C source/industrial_comms/profinet_device/icss_fwhal -f makefile.irt_mii.am263px.$(subst profinet_device_irt_mii_icss_fwhal_,,$@) all

$(BUILD_COMBO_profinet_device_rt_mrp_mii_icss_fwhal):
	$(MAKE) -C source/industrial_comms/profinet_device/icss_fwhal -f makefile.rt_mrp_mii.am263px.$(subst profinet_device_rt_mrp_mii_icss_fwhal_,,$@) all


# Various Component Clean Targets
BUILD_COMBO_CLEAN_ethercat_slave_icss_fwhal = ethercat_slave_icss_fwhal_r5f.ti-arm-clang_clean
BUILD_COMBO_CLEAN_ethernetip_adapter_mii_icss_fwhal = ethernetip_adapter_mii_icss_fwhal_r5f.ti-arm-clang_clean
BUILD_COMBO_CLEAN_ethernetip_adapter_lwip_contrib = ethernetip_adapter_lwip_contrib_r5f.ti-arm-clang_clean
BUILD_COMBO_CLEAN_ethernetip_adapter_lwip_freertos = ethernetip_adapter_lwip_freertos_r5f.ti-arm-clang_clean
BUILD_COMBO_CLEAN_profinet_device_irt_mii_icss_fwhal = profinet_device_irt_mii_icss_fwhal_r5f.ti-arm-clang_clean
BUILD_COMBO_CLEAN_profinet_device_rt_mrp_mii_icss_fwhal = profinet_device_rt_mrp_mii_icss_fwhal_r5f.ti-arm-clang_clean

# Combine all Components Clean
BUILD_COMBO_CLEAN_ALL = $(BUILD_COMBO_CLEAN_ethercat_slave_icss_fwhal) $(BUILD_COMBO_CLEAN_ethernetip_adapter_mii_icss_fwhal) $(BUILD_COMBO_CLEAN_ethernetip_adapter_lwip_contrib) $(BUILD_COMBO_CLEAN_ethernetip_adapter_lwip_freertos) $(BUILD_COMBO_CLEAN_profinet_device_irt_mii_icss_fwhal) $(BUILD_COMBO_CLEAN_profinet_device_rt_mrp_mii_icss_fwhal)

# Combine all Pre-built Components Clean
BUILD_COMBO_PREBUILT_CLEAN_ALL =

libs-clean: $(BUILD_COMBO_CLEAN_ALL)

libs-prebuilt-clean: $(BUILD_COMBO_PREBUILT_CLEAN_ALL)

$(BUILD_COMBO_CLEAN_ethercat_slave_icss_fwhal):
	$(MAKE) -C source/industrial_comms/ethercat_slave/icss_fwhal -f makefile.am263px.$(subst ethercat_slave_icss_fwhal_,,$(subst _clean,,$@)) clean

$(BUILD_COMBO_CLEAN_ethernetip_adapter_mii_icss_fwhal):
	$(MAKE) -C source/industrial_comms/ethernetip_adapter/icss_fwhal -f makefile.mii.am263px.$(subst ethernetip_adapter_mii_icss_fwhal_,,$(subst _clean,,$@)) clean

$(BUILD_COMBO_CLEAN_ethernetip_adapter_lwip_contrib):
	$(MAKE) -C source/industrial_comms/ethernetip_adapter/stack/lwip -f makefile.contrib.am263px.$(subst ethernetip_adapter_lwip_contrib_,,$(subst _clean,,$@)) clean

$(BUILD_COMBO_CLEAN_ethernetip_adapter_lwip_freertos):
	$(MAKE) -C source/industrial_comms/ethernetip_adapter/stack/lwip -f makefile.stack.am263px.$(subst ethernetip_adapter_lwip_freertos_,,$(subst _clean,,$@)) clean

$(BUILD_COMBO_CLEAN_profinet_device_irt_mii_icss_fwhal):
	$(MAKE) -C source/industrial_comms/profinet_device/icss_fwhal -f makefile.irt_mii.am263px.$(subst profinet_device_irt_mii_icss_fwhal_,,$(subst _clean,,$@)) clean

$(BUILD_COMBO_CLEAN_profinet_device_rt_mrp_mii_icss_fwhal):
	$(MAKE) -C source/industrial_comms/profinet_device/icss_fwhal -f makefile.rt_mrp_mii.am263px.$(subst profinet_device_rt_mrp_mii_icss_fwhal_,,$(subst _clean,,$@)) clean


# Various Component Scrub Targets
BUILD_COMBO_SCRUB_ethercat_slave_icss_fwhal = ethercat_slave_icss_fwhal_r5f.ti-arm-clang_scrub_scrub
BUILD_COMBO_SCRUB_ethernetip_adapter_mii_icss_fwhal = ethernetip_adapter_mii_icss_fwhal_r5f.ti-arm-clang_scrub_scrub
BUILD_COMBO_SCRUB_ethernetip_adapter_lwip_contrib = ethernetip_adapter_lwip_contrib_r5f.ti-arm-clang_scrub_scrub
BUILD_COMBO_SCRUB_ethernetip_adapter_lwip_freertos = ethernetip_adapter_lwip_freertos_r5f.ti-arm-clang_scrub_scrub
BUILD_COMBO_SCRUB_profinet_device_irt_mii_icss_fwhal = profinet_device_irt_mii_icss_fwhal_r5f.ti-arm-clang_scrub_scrub
BUILD_COMBO_SCRUB_profinet_device_rt_mrp_mii_icss_fwhal = profinet_device_rt_mrp_mii_icss_fwhal_r5f.ti-arm-clang_scrub_scrub

# Combine all Components Scrub Targets
BUILD_COMBO_SCRUB_ALL = $(BUILD_COMBO_SCRUB_ethercat_slave_icss_fwhal) $(BUILD_COMBO_SCRUB_ethernetip_adapter_mii_icss_fwhal) $(BUILD_COMBO_SCRUB_ethernetip_adapter_lwip_contrib) $(BUILD_COMBO_SCRUB_ethernetip_adapter_lwip_freertos) $(BUILD_COMBO_SCRUB_profinet_device_irt_mii_icss_fwhal) $(BUILD_COMBO_SCRUB_profinet_device_rt_mrp_mii_icss_fwhal)

# Combine all Pre-built Components Scrub Targets
BUILD_COMBO_PREBUILT_SCRUB_ALL =

libs-scrub: $(BUILD_COMBO_SCRUB_ALL)

libs-prebuilt-scrub: $(BUILD_COMBO_PREBUILT_SCRUB_ALL)

$(BUILD_COMBO_SCRUB_ethercat_slave_icss_fwhal):
	$(MAKE) -C source/industrial_comms/ethercat_slave/icss_fwhal -f makefile.am263px.$(subst ethercat_slave_icss_fwhal_,,$(subst _scrub,,$@)) scrub

$(BUILD_COMBO_SCRUB_ethernetip_adapter_mii_icss_fwhal):
	$(MAKE) -C source/industrial_comms/ethernetip_adapter/icss_fwhal -f makefile.mii.am263px.$(subst ethernetip_adapter_mii_icss_fwhal_,,$(subst _scrub,,$@)) scrub

$(BUILD_COMBO_SCRUB_ethernetip_adapter_lwip_contrib):
	$(MAKE) -C source/industrial_comms/ethernetip_adapter/stack/lwip -f makefile.contrib.am263px.$(subst ethernetip_adapter_lwip_contrib_,,$(subst _scrub,,$@)) scrub

$(BUILD_COMBO_SCRUB_ethernetip_adapter_lwip_freertos):
	$(MAKE) -C source/industrial_comms/ethernetip_adapter/stack/lwip -f makefile.stack.am263px.$(subst ethernetip_adapter_lwip_freertos_,,$(subst _scrub,,$@)) scrub

$(BUILD_COMBO_SCRUB_profinet_device_irt_mii_icss_fwhal):
	$(MAKE) -C source/industrial_comms/profinet_device/icss_fwhal -f makefile.irt_mii.am263px.$(subst profinet_device_irt_mii_icss_fwhal_,,$(subst _scrub,,$@)) scrub

$(BUILD_COMBO_SCRUB_profinet_device_rt_mrp_mii_icss_fwhal):
	$(MAKE) -C source/industrial_comms/profinet_device/icss_fwhal -f makefile.rt_mrp_mii.am263px.$(subst profinet_device_rt_mrp_mii_icss_fwhal_,,$(subst _scrub,,$@)) scrub


BUILD_COMBO_EXAMPLE_ALL =
# Various Example Targets
BUILD_COMBO_EXAMPLE_ALL += ethercat_slave_cia402_demo_am263px-lp_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += ethercat_slave_ctt_demo_am263px-lp_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += ethercat_slave_simple_demo_am263px-lp_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += ethernetip_adapter_generic_device_mii_demo_am263px-lp_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += ethernetip_adapter_discrete_io_device_mii_demo_am263px-lp_r5fss0-0_freertos_ti-arm-clang
# Various System Example Targets

BUILD_COMBO_EXAMPLE_PRIVATE_ALL =
# Various Private Example Targets
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += ethercat_slave_beckhoff_ssc_demo_am263px-lp_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += ethercat_slave_beckhoff_ssc_demo_am263px-cc_r5fss0-0_freertos_ti-arm-clang
# Various Private System Example Targets

examples: $(BUILD_COMBO_EXAMPLE_ALL)

examples-private: $(BUILD_COMBO_EXAMPLE_PRIVATE_ALL)

 ethercat_slave_beckhoff_ssc_demo_am263px-lp_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/industrial_comms/ethercat_slave_beckhoff_ssc_demo/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile all

 ethercat_slave_beckhoff_ssc_demo_am263px-cc_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/industrial_comms/ethercat_slave_beckhoff_ssc_demo/am263px-cc/r5fss0-0_freertos/ti-arm-clang -f makefile all

 ethercat_slave_cia402_demo_am263px-lp_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/industrial_comms/ethercat_slave_demo/device_profiles/402_cia/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile all

 ethercat_slave_ctt_demo_am263px-lp_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/industrial_comms/ethercat_slave_demo/device_profiles/ctt/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile all

 ethercat_slave_simple_demo_am263px-lp_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/industrial_comms/ethercat_slave_demo/device_profiles/401_simple/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile all

 ethernetip_adapter_generic_device_mii_demo_am263px-lp_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/industrial_comms/ethernetip_adapter_demo/device_profiles/generic_device/mii/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile all

 ethernetip_adapter_discrete_io_device_mii_demo_am263px-lp_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/industrial_comms/ethernetip_adapter_demo/device_profiles/discrete_io_device/mii/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile all


BUILD_COMBO_EXAMPLE_CLEAN_ALL =
# Various Example Clean Targets
BUILD_COMBO_EXAMPLE_CLEAN_ALL += ethercat_slave_cia402_demo_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += ethercat_slave_ctt_demo_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += ethercat_slave_simple_demo_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += ethernetip_adapter_generic_device_mii_demo_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += ethernetip_adapter_discrete_io_device_mii_demo_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean
# Various System Example Clean Targets

BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL =
# Various Private Example Targets
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += ethercat_slave_beckhoff_ssc_demo_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += ethercat_slave_beckhoff_ssc_demo_am263px-cc_r5fss0-0_freertos_ti-arm-clang_clean
# Various Private System Example Targets

examples-clean: $(BUILD_COMBO_EXAMPLE_CLEAN_ALL)

examples-private-clean: $(BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL)

 ethercat_slave_beckhoff_ssc_demo_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/industrial_comms/ethercat_slave_beckhoff_ssc_demo/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 ethercat_slave_beckhoff_ssc_demo_am263px-cc_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/industrial_comms/ethercat_slave_beckhoff_ssc_demo/am263px-cc/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 ethercat_slave_cia402_demo_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/industrial_comms/ethercat_slave_demo/device_profiles/402_cia/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 ethercat_slave_ctt_demo_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/industrial_comms/ethercat_slave_demo/device_profiles/ctt/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 ethercat_slave_simple_demo_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/industrial_comms/ethercat_slave_demo/device_profiles/401_simple/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 ethernetip_adapter_generic_device_mii_demo_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/industrial_comms/ethernetip_adapter_demo/device_profiles/generic_device/mii/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 ethernetip_adapter_discrete_io_device_mii_demo_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/industrial_comms/ethernetip_adapter_demo/device_profiles/discrete_io_device/mii/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile clean


BUILD_COMBO_EXAMPLE_SCRUB_ALL =
# Various Example Scrub Targets
BUILD_COMBO_EXAMPLE_SCRUB_ALL += ethercat_slave_cia402_demo_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += ethercat_slave_ctt_demo_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += ethercat_slave_simple_demo_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += ethernetip_adapter_generic_device_mii_demo_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += ethernetip_adapter_discrete_io_device_mii_demo_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub
# Various System Example Scrub Targets

BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL =
# Various Private Example Targets
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += ethercat_slave_beckhoff_ssc_demo_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += ethercat_slave_beckhoff_ssc_demo_am263px-cc_r5fss0-0_freertos_ti-arm-clang_scrub
# Various Private System Example Targets

examples-scrub: $(BUILD_COMBO_EXAMPLE_SCRUB_ALL)

examples-scrub-private: $(BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL)

 ethercat_slave_beckhoff_ssc_demo_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/industrial_comms/ethercat_slave_beckhoff_ssc_demo/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 ethercat_slave_beckhoff_ssc_demo_am263px-cc_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/industrial_comms/ethercat_slave_beckhoff_ssc_demo/am263px-cc/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 ethercat_slave_cia402_demo_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/industrial_comms/ethercat_slave_demo/device_profiles/402_cia/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 ethercat_slave_ctt_demo_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/industrial_comms/ethercat_slave_demo/device_profiles/ctt/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 ethercat_slave_simple_demo_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/industrial_comms/ethercat_slave_demo/device_profiles/401_simple/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 ethernetip_adapter_generic_device_mii_demo_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/industrial_comms/ethernetip_adapter_demo/device_profiles/generic_device/mii/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 ethernetip_adapter_discrete_io_device_mii_demo_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/industrial_comms/ethernetip_adapter_demo/device_profiles/discrete_io_device/mii/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile scrub


.PHONY: all clean scrub help
.PHONY: libs libs-clean libs-scrub
.PHONY: libs-private
.PHONY: libs-prebuilt libs-prebuilt-clean libs-prebuilt-scrub
.PHONY: examples examples-clean examples-scrub
.PHONY: examples-private examples-private-clean examples-private-scrub
.PHONY: $(BUILD_COMBO_ALL) $(BUILD_COMBO_CLEAN_ALL) $(BUILD_COMBO_SCRUB_ALL)
.PHONY: $(BUILD_COMBO_EXAMPLE_ALL) $(BUILD_COMBO_EXAMPLE_CLEAN_ALL) $(BUILD_COMBO_EXAMPLE_SCRUB_ALL)
.PHONY: $(BUILD_COMBO_EXAMPLE_PRIVATE_ALL) $(BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL) $(BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL)
